Todo list add
faisalakb/Todo_List pull request #2
Opened 2023-05-09 15:42 UTC by faisalakb

Please check my Todo list PR that has the following features: 💯
- Create an array of objects. 👍
- use local storage. 👍
- add dynamic HTML. 👍
- Handle Folder and file structure using WebPack. 👍

2023-05-09 16:02 UTC, Davidosky007 requested changes
Hi @faisalakb 👋, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
* No linter errors 👍 
* ES6 syntax used properly 👍 
* Good looking readme 👍 

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @davidsoky007 in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-09 16:02 UTC, Davidosky007 commented on src/index.js
> +let list = [];
* According to the requirements you are expected to 
* Create an index.js file and set an array of some simple to-do tasks (array of objects).
* Write a function to iterate over the tasks array and populate an HTML list item element for each task
* On page load render the dynamically created list of tasks in the dedicated placeholder. The list should appear in order of the index values for each task.
* Kindly make the necessary adjustments 
![image](https://github.com/faisalakb/Todo_List/assets/52497246/493f5944-ee12-49ca-b934-c26915ad0a50)

2023-05-10 10:40 UTC, AlphaNtihinduka approved these changes
# STATUS: APPROVED :green_circle: :clap: 
## Hi @faisalakb 🙋‍♂️, 

Your project is complete!  There is nothing else to say other than... Great job 👏 

![approved-accepted](https://user-images.githubusercontent.com/99394374/212473432-e725752b-8682-4dbb-993e-9e466dbe7acb.gif)

Congratulations! 🎉 
TO HIGHLIGHT:

- Listing the todo list items dynamically ✔️
- Correct use of use functional component that iterates over the array of objects ✔️
- Well-structured files :heavy_check_mark: 


Now you can merge this branch and move on :1st_place_medal: 


## Optional suggestions
- Kindly refer to the inline optional suggestions made. Ensure to apply them to have a professional project that suits recruiters' needs.

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

HAPPY CODING AND GOOD LUCK WITH THE COMING ONES :crossed_fingers: :four_leaf_clover:

2023-05-10 10:52 UTC, faisalakb commented
Thanks for Review

2023-05-13 07:42 UTC, merged